### ISSUE TITLE
Red Faction Guerrilla support?

### ISSUE THREAD

**Issue by Rast1234** [tomjepp/ThomasJepp.SaintsRow#1]
Hello, is it possible to use your tools with Red Faction Guerrilla archives? There is similar project here: https://bitbucket.org/minimaul/gibbedvolition (is that yours?), it does mostly same things but lacks recursive extractor and can not auto-update asm_pc files

**Comment by tomjepp** [comment]
On 04/03/2015 03:46, Rostislav Kirillov wrote:
> Hello, is it possible to use your tools with Red Faction Guerrilla
> archives? There is similar project here:
> https://bitbucket.org/minimaul/gibbedvolition (is that yours?), it does
> mostly same things but lacks recursive extractor and can not auto-update
> asm_pc files
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomjepp/ThomasJepp.SaintsRow/issues/1>.
> 

That repository is mine, yes - it's a mercurial copy of one from
http://gib.me/ (the original is SVN) with a few bugfixes. I *think* that
one can do RF:G - but the ThomasJepp.SaintsRow tools definitely can't at
the moment.

-- 
Thomas Jepp
tom@tomjepp.co.uk

**Comment by Rast1234** [comment]
Thanks. You got specs for game resources somewhere or reverse-engineered them?
Do SR and RFG file formats (vpp, str2, asm) differ in general? Or they are mostly identical?

**Comment by tomjepp** [comment]
On 05/03/2015 06:46, Rostislav Kirillov wrote:
> Thanks. You got specs for game resources somewhere or reverse-engineered
> them?
> Do SR and RFG file formats (vpp, str2, asm) differ in general? Or they
> are mostly identical?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomjepp/ThomasJepp.SaintsRow/issues/1#issuecomment-77315387>.
> 

The initial set were reverse engineered, but Volition are very helpful
these days with regard to Saints Row since they were bought by Deep
Silver. Red Faction isn't owned by Volition any more so it'd be up to
the new devs if they want to help you out or not.

Volition file formats tend to start with a 32-bit int with an
identifier, then a second 32-bit int with a version - if the version's
the same then the file format should be the same.

I seem to think that RF:G uses the same format for vpp_pc and str2_pc
files as Saints Row: The Third does - version 6. If that's the case,
take a look at:
https://www.saintsrowmods.com/forum/threads/asm-and-vpp-file-formats.8448/

-- 
Thomas Jepp
tom@tomjepp.co.uk

**Comment by Rast1234** [comment]
I'll take a look, cheers!
